services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - /opt/docker/homepage:/app/config # Make sure your local config directory exists
      - /opt/docker/homepage/images:/app/public/images # mount a path to where your images are kept
    env_file:
      - .env
    environment:
      HOMEPAGE_ALLOWED_HOSTS: gethomepage.dev,192.168.5.31:3000 # required, may need port. See gethomepage.dev/installation/#homepage_allowed_hosts
      PUID: $PUID
      PGID: $PGID