---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- System:
    - Proxmox:
        icon: proxmox.png
        href: {{HOMEPAGE_VAR_PROXMOX_IP_URL}}
        widget:
          type: proxmox
          url: {{HOMEPAGE_VAR_PROXMOX_IP_URL}}
          username: {{HOMEPAGE_VAR_PROXMOX_API_ID}} 
          password: {{HOMEPAGE_VAR_PROXMOX_API_KEY}}
    - Komodo:
        id: col-large__komodo
        icon: komodo
        server: f-si-komodo
        container: komodo-core-1
        href: {{HOMEPAGE_VAR_KOMODO_IP_URL}}
        showStats: false
        widget:
          type: komodo
          url: {{HOMEPAGE_VAR_KOMODO_IP_URL}}
          key: {{HOMEPAGE_VAR_KOMODO_API_KEY}}
          secret: {{HOMEPAGE_VAR_KOMODO_SECRET}}
          showSummary: false # optional, default: false. Takes precedence over showStacks
          showStacks: true # optional, default: false
    - Synology:
        id: col-small__synology
        icon: synology
        href: {{HOMEPAGE_VAR_SYNOLOGY_IP_URL}}
        widget:
          type: diskstation
          url: {{HOMEPAGE_VAR_SYNOLOGY_IP_URL}}
          username: {{HOMEPAGE_VAR_SYNOLOGY_USERNAME}}
          password: {{HOMEPAGE_VAR_SYNOLOGY_PASSWORD}}

- Main:
    - Plex:
        id: __plex
        icon: plex
        href: {{HOMEPAGE_VAR_PLEX_URL}}
        widget:
          type: plex
          url: {{HOMEPAGE_VAR_PLEX_URL}} 
          key: {{HOMEPAGE_VAR_PLEX_API_KEY}} # see https://www.plexopedia.com/plex-media-server/general/plex-token/

- Weather:
    - "":
        widget:
          type: weather
          provider: open-meteo # or weatherapi
          label: Duluth # optional
          latitude: {{HOMEPAGE_VAR_WEATHER_LATITUDE}} # e.g., 50.4501
          longitude: {{HOMEPAGE_VAR_WEATHER_LONGITUDE}} # e.g., 30.5234
          timezone: Americas/Duluth # optional
          units: imperial # or metric
          cache: 5 # Time in minutes to cache API responses, to stay within limits
          format: # optional, Intl.NumberFormat options
            maximumFractionDigits: 1

- Calendar:
    - Upcoming Media Releases:
        icon: mdi-popcorn
        widget:
          type: calendar
          firstDayInWeek: monday # optional - defaults to monday
          view: monthly # optional - possible values monthly, agenda
          maxEvents: 10 # optional - defaults to 10
          showTime: true # optional - show time for event happening today - defaults to false