---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- System:
    - Proxmox:
        id: col-3x__proxmox
        icon: proxmox.png
        href: {{HOMEPAGE_VAR_PROXMOX_IP_URL}}
        widget:
          type: proxmox
          url: {{HOMEPAGE_VAR_PROXMOX_IP_URL}}
          username: {{HOMEPAGE_VAR_PROXMOX_API_ID}} 
          password: {{HOMEPAGE_VAR_PROXMOX_API_KEY}}
    - Komodo:
        id: col-12-21__komodo
        icon: komodo
        server: f-si-komodo
        container: komodo-core-1
        href: {{HOMEPAGE_VAR_KOMODO_IP_URL}}
        showStats: false
        widget:
          type: komodo
          url: {{HOMEPAGE_VAR_KOMODO_IP_URL}}
          key: {{HOMEPAGE_VAR_KOMODO_API_KEY}}
          secret: {{HOMEPAGE_VAR_KOMODO_SECRET}}
          showSummary: false # optional, default: false. Takes precedence over showStacks
          showStacks: true # optional, default: false
          fields: ["running", "down", "total"] # Allowed fields (max 4): ["total", "running", "stopped", "unhealthy", "unknown"]
    - Synology:
        id: col-9-21__synology
        icon: synology
        href: {{HOMEPAGE_VAR_SYNOLOGY_IP_URL}}
        widget:
          type: diskstation
          url: {{HOMEPAGE_VAR_SYNOLOGY_IP_URL}}
          username: {{HOMEPAGE_VAR_SYNOLOGY_USERNAME}}
          password: {{HOMEPAGE_VAR_SYNOLOGY_PASSWORD}}
          fields: ["volumeAvailable"]

- Main:
    - Plex:
        id: col-3x__plex
        icon: plex
        href: {{HOMEPAGE_VAR_PLEX_URL}}
        widget:
          type: plex
          url: {{HOMEPAGE_VAR_PLEX_URL}} 
          key: {{HOMEPAGE_VAR_PLEX_API_KEY}} # see https://www.plexopedia.com/plex-media-server/general/plex-token/

- Admin:
    - Speedtest:
        id: col-max__speedtest-tracker
        icon: speedtest-tracker
        href: {{HOMEPAGE_VAR_SPEEDTEST_TRACKER_URL}}
        server: REDACTED
        container: speedtest-tracker
        widget:
          type: speedtest
          url: {{HOMEPAGE_VAR_SPEEDTEST_TRACKER_IP_URL}}

- Weather:
    - "":
        id: col-max__weather
        widget:
          type: iframe
          name: iframe-home-assistant-weather
          src: "{{HOMEPAGE_VAR_HOMEASSISTANT_URL}}/dashboard-homepage/weather?kiosk"
          classes: iframe-home-assistant-weather
          referrerPolicy: same-origin # optional, no default
          allowPolicy: fullscreen # optional, no default
          allowFullscreen: true # optional, default: true
          loadingStrategy: eager # optional, default: eager
          allowScrolling: no # optional, default: yes   

- Monitoring & Networking:
    - Home Assistant:
        id: col-1-2__home-assistant
        icon: home-assistant
        href: {{HOMEPAGE_VAR_HOMEASSISTANT_URL}}
        server: REDACTED
        container: homeassistant
        widget:
          type: homeassistant
          url: {{HOMEPAGE_VAR_HOMEASSISTANT_URL}}
          key: {{HOMEPAGE_VAR_HOMEASSISTANT_TOKEN}}

- Calendar:
    - Holidays, Movies, NFL:
        widget:
          type: calendar
          firstDayInWeek: monday # optional - defaults to monday
          view: monthly # optional - possible values monthly, agenda
          maxEvents: 10 # optional - defaults to 10
          showTime: true # optional - show time for event happening today - defaults to false
          integrations: # optional
            - type: ical
              url: https://www.thunderbird.net/media/caldata/autogen/USHolidays.ics
              name: Holiday
              color: purple
              params: # optional - additional params for the service
                showName: true # optional - show name before event title in event line - defaults to false
            - type: ical
              url: https://raw.githubusercontent.com/callaars/film-calendar/refs/heads/main/calendars/tmdb_release_calendar_US_theatrical.ics
              name: Movie
              color: emerald
              params: # optional - additional params for the service
                showName: true # optional - show name before event title in event line - defaults to false
            - type: ical
              url: https://fancalendar.app/api/subscription/ec2f87a409995522.ics
              name: NFL
              color: red
              params: # optional - additional params for the service
                showName: true # optional - show name before event title in event line - defaults to false