---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- System:
    - Proxmox:
        icon: proxmox.png
        href: {{HOMEPAGE_VAR_PROXMOX_IP_URL}}
        weight: "0"
        widget:
          type: proxmox
          url: {{HOMEPAGE_VAR_PROXMOX_IP_URL}}
          username: {{HOMEPAGE_VAR_PROXMOX_API_ID}} 
          password: {{HOMEPAGE_VAR_PROXMOX_API_KEY}}
    - Komodo:
        id: col-1-3__komodo
        icon: komodo
        server: f-si-komodo
        container: komodo-core-1
        href: {{HOMEPAGE_VAR_KOMODO_IP_URL}}
        showStats: false
        widget:
          type: komodo
          url: {{HOMEPAGE_VAR_KOMODO_IP_URL}}
          key: {{HOMEPAGE_VAR_KOMODO_API_KEY}}
          secret: {{HOMEPAGE_VAR_KOMODO_SECRET}}
          showSummary: false # optional, default: false. Takes precedence over showStacks
          showStacks: true # optional, default: false
          fields: ["running", "down", "total"] # Allowed fields (max 4): ["total", "running", "stopped", "unhealthy", "unknown"]
    - Synology:
        id: col-1-1__synology
        icon: synology
        href: {{HOMEPAGE_VAR_SYNOLOGY_IP_URL}}
        widget:
          type: diskstation
          url: {{HOMEPAGE_VAR_SYNOLOGY_IP_URL}}
          username: {{HOMEPAGE_VAR_SYNOLOGY_USERNAME}}
          password: {{HOMEPAGE_VAR_SYNOLOGY_PASSWORD}}
          fields: ["volumeAvailable"]

- Calendar:
    - Calendar:
        widget:
          type: calendar
          firstDayInWeek: sunday # optional - defaults to monday
          view: monthly # optional - possible values monthly, agenda
          maxEvents: 10 # optional - defaults to 10
          showTime: true # optional - show time for event happening today - defaults to false
          timezone: America/New_York # optional and only when timezone is not detected properly (slightly slower performance) - force timezone for ical events (if it's the same - no change, if missing or different in ical - will be converted to this timezone)
          integrations: # optional
            - type: radarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr, lidarr, readarr, ical
              service_group: Media # group name where widget exists
              service_name: Radarr # service name for that widget
              baseUrl: {{HOMEPAGE_VAR_SERVARR_IP}} # optional - adds links to sonarr/radarr pages
              params: # optional - additional params for the service
                unmonitored: true # optional - defaults to false, used with *arr stack
            - type: sonarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr, lidarr, readarr, ical
              service_group: Media # group name where widget exists
              service_name: Sonarr # service name for that widget
              baseUrl: {{HOMEPAGE_VAR_SERVARR_IP}} # optional - adds links to sonarr/radarr pages
              params: # optional - additional params for the service
                unmonitored: true # optional - defaults to false, used with *arr stack
    
- "":
    - Agenda:
        widget:
          type: calendar
          view: agenda
          maxEvents: 10 # optional - defaults to 10
          showTime: true # optional - show time for event happening today - defaults to false
          previousDays: 3 # optional - shows events since three days ago - defaults to 0
          integrations: # same as in Monthly view example
            - type: radarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr, lidarr, readarr, ical
              service_group: Media # group name where widget exists
              service_name: Radarr # service name for that widget
              baseUrl: {{HOMEPAGE_VAR_SERVARR_IP}} # optional - adds links to sonarr/radarr pages
              params: # optional - additional params for the service
                unmonitored: true # optional - defaults to false, used with *arr stack
            - type: sonarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr, lidarr, readarr, ical
              service_group: Media # group name where widget exists
              service_name: Sonarr # service name for that widget
              baseUrl: {{HOMEPAGE_VAR_SERVARR_IP}}  # optional - adds links to sonarr/radarr pages
              params: # optional - additional params for the service
                unmonitored: true # optional - defaults to false, used with *arr stack

- Apps:
    - Plex:
        icon: plex
        href: {{HOMEPAGE_VAR_PLEX_URL}}
        weight: "0"
        widget:
          type: plex
          url: {{HOMEPAGE_VAR_PLEX_URL}} 
          key: {{HOMEPAGE_VAR_PLEX_API_KEY}} # see https://www.plexopedia.com/plex-media-server/general/plex-token/

- Monitoring & Networking:
    - Home Assistant:
        icon: home-assistant
        href: {{HOMEPAGE_VAR_HOMEASSISTANT_URL}}
        server: REDACTED
        container: homeassistant
        widget:
          type: homeassistant
          url: {{HOMEPAGE_VAR_HOMEASSISTANT_URL}}
          key: {{HOMEPAGE_VAR_HOMEASSISTANT_TOKEN}}

