---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

title: Fey Server Infrastructure

background: 
  image: /images/cyberpunk.jpg
  blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 70 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 70 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 100 # 0-100
cardBlur: md # or sm, lg
headerStyle: boxedWidgets #underlined # or boxed, boxedWidgets, clean
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true
  provider: bing # google, duckduckgo, bing, baidu, brave or custom
theme: dark
color: yellow
hideVersion: true
useEqualHeights: true
showStats: false
statusStyle: 'dot'
hideErrors: true


layout:
  Row1:
    style: row
    columns: 3
    header: false
    System:
      icon: mdi-desktop-classic-#ffffff
    Calendar:
      style: row
      columns: 2
      icon: mdi-calendar-month-outline-#ffffff
    Apps:
      icon: mdi-shield-crown-outline-#ffffff
  Row2:
    style: row
    columns: 4
    header: false
    Admin:
      icon: mdi-account-box-outline-#ffffff
    Media Management:
      icon: si-vlcmediaplayer-#ffffff
    Monitoring & Networking:
      icon: mdi-home-analytics-#ffffff
    Tools:
      icon: mdi-application-brackets-outline-#ffffff
  Bookmarks:
    icon: mdi-bookmark-multiple-outline-#ffffff