---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

title: Fey Server Infrastructure

background: 
  image: /images/cyberpunk.jpg
  opacity: 70 # 0-100

cardBlur: md # xs, md, etc... see https://tailwindcss.com/docs/backdrop-blur

theme: dark # or light

color: yellow

blockHighlights:
  levels:
    good: "bg-emerald-500/40 text-emerald-950 dark:bg-emerald-900/60 dark:text-emerald-400"
    warn: "bg-amber-300/30 text-amber-900 dark:bg-amber-900/30 dark:text-amber-200"
    danger: "bg-rose-700/45 text-rose-200 dark:bg-rose-950/70 dark:text-rose-400"

iconStyle: theme # optional, defaults to gradient
useEqualHeights: true
layout:
  Row1:
    style: row
    columns: 3
    header: false
    System:
      icon: mdi-desktop-classic-#ffffff
    Calendar:
      style: row
      columns: 2
      icon: mdi-calendar-month-outline-#ffffff
    Apps:
      icon: mdi-shield-crown-outline-#ffffff
  Row2:
    style: row
    columns: 4
    header: false
    Admin:
      icon: mdi-account-box-outline-#ffffff
    Media Management:
      icon: si-vlcmediaplayer-#ffffff
    Monitoring & Networking:
      icon: mdi-home-analytics-#ffffff
    Tools:
      icon: mdi-application-brackets-outline-#ffffff
  Bookmarks:
    icon: mdi-bookmark-multiple-outline-#ffffff

headerStyle: boxedWidgets #underlined # or boxed, boxedWidgets, clean

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true
  provider: bing # google, duckduckgo, bing, baidu, brave or custom

hideVersion: true

showStats: false

statusStyle: 'basic'

hideErrors: true