---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

title: Fey Server Infrastructure

background: 
  image: /images/cyberpunk.jpg
  opacity: 70 # 0-100

cardBlur: md # xs, md, etc... see https://tailwindcss.com/docs/backdrop-blur

theme: dark # or light

color: teal

blockHighlights:
  levels:
    good: "bg-emerald-500/40 text-emerald-950 dark:bg-emerald-900/60 dark:text-emerald-400"
    warn: "bg-amber-300/30 text-amber-900 dark:bg-amber-900/30 dark:text-amber-200"
    danger: "bg-rose-700/45 text-rose-200 dark:bg-rose-950/70 dark:text-rose-400"

iconStyle: theme # optional, defaults to gradient
useEqualHeights: true
layout:
  Info:
    icon: mdi-information-outline-#ffffff
    style: row
    columns: 4
  System:
    icon: mdi-desktop-classic-#ffffff
    tab: Services
  Apps:
    icon: mdi-shield-crown-outline-#ffffff
    tab: Services
  Admin:
    icon: mdi-account-box-outline-#ffffff
    tab: Services
  Media Management:
    icon: si-vlcmediaplayer-#ffffff
    tab: Services
  Monitoring & Networking:
    icon: mdi-home-analytics-#ffffff
    tab: Services
  Tools:
    icon: mdi-application-brackets-outline-#ffffff
    tab: Services
  Bookmarks:
    icon: mdi-bookmark-multiple-outline-#ffffff
    tab: Services
  Grafana Dashboard:
    header: false
    tab: Grafana


headerStyle: boxedWidgets #underlined # or boxed, boxedWidgets, clean

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true
  provider: bing # google, duckduckgo, bing, baidu, brave or custom

hideVersion: true

showStats: false

statusStyle: 'basic'

hideErrors: false