---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/docker/

# my-docker:
#   host: 127.0.0.1
#   port: 2375

# my-docker:
#   socket: /var/run/docker.sock

f-si-komodo:
  host: 192.168.5.102
  port: 2375

f-si-servarr:
  host: 192.168.5.103
  port: 2375