---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

title: Fey Server Infrastructure

background: 
  image: /images/cyberpunk.jpg
  blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 70 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 70 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 100 # 0-100
cardBlur: md # or sm, lg
headerStyle: boxedWidgets #underlined # or boxed, boxedWidgets, clean
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true
  provider: bing # google, duckduckgo, bing, baidu, brave or custom
theme: dark
color: yellow
hideVersion: true
useEqualHeights: true
showStats: false
statusStyle: 'dot'
hideErrors: true


layout:
  System:
    icon: mdi-desktop-classic-#ffffff
    columns: 4
  Main:
    icon: mdi-shield-crown-outline-#ffffff
    columns: 4
  Admin:
    icon: mdi-account-box-outline-#ffffff
    columns: 4
  Weather:
    icon: mdi-weather-hazy-#ffffff
    columns: 4
  Media Management:
    icon: si-vlcmediaplayer-#ffffff
    columns: 4
  Monitoring & Networking:
    icon: mdi-home-analytics-#ffffff
    columns: 4
  Tools:
    icon: mdi-application-brackets-outline-#ffffff
    columns: 4
  Calendar:
    icon: mdi-calendar-month-outline-#ffffff
    columns: 4
  Bookmarks:
    icon: mdi-bookmark-multiple-outline-#ffffff
    columns: 4